
version: "3.9"

services:
  database:
    image: postgres
    container_name: database_pg
    restart: always
    ports:
      - 5431:5432 
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=login
      - POSTGRES_DB=loginuser
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local